const LOGIN = "LOGIN"
const REGISTER = "REGISTER"
const USER = "USER"
//const PATH = "http://localhost:3001/api/"
const PATH = "https://escrow-api.herokuapp.com/api/"
const INVITEUSER = 'INVITEUSER'
const COMPANY = 'COMPANY'
const MONTH = ['January','February', 'March', 'April','May','June','July','August','September','October','November','December']
const TRANSACTIONS = 'TRANSACTIONS'
const MESSAGE = 'MESSAGE'
const COMPLETEPROFILE = 'COMPLETEPROFILE'
const LOGOUT = 'LOGOUT';
const COUNTRIES = 'COUNTRIES';
const STATES = 'STATES';
const CITIES = 'CITIES';
const WITNESSES = 'WITNESSES';
const ORDERS = 'ORDERS';
const CHATMESSAGES = 'CHATMESSAGES';
const WITNESS_PENDING = 'WITNESS_PENDING'
const OTHERPARTY_PENDING = 'OTHERPARTY_PENDING'
const VIEWTRANSACTION = 'VIEWTRANSACTION'
const OTHERPARTYINFORMATION = 'OTHERPARTYINFORMATION'
const OTHERPARTYINFORMATION_INVITE = 'OTHERPARTYINFORMATION_INVITE'
const AGREEMENT = 'AGREEMENT'
const SENDMESSAGE = 'SENDMESSAGE'
const VIEWWITNESSTRANSACTION = 'VIEWWITNESSTRANSACTION'
const WITNESSTRANSACTIONS = 'WITNESSTRANSACTIONS'
const UPDATEUSER = 'UPDATEUSER'



export {
    LOGIN,
    LOGOUT,
    AGREEMENT,
    UPDATEUSER,
    WITNESSTRANSACTIONS,
    VIEWWITNESSTRANSACTION,
    SENDMESSAGE,
    VIEWTRANSACTION,
    COMPLETEPROFILE,
    WITNESS_PENDING,
    OTHERPARTY_PENDING,
    OTHERPARTYINFORMATION,
    OTHERPARTYINFORMATION_INVITE,
    STATES,
    COUNTRIES,
    CITIES,
    REGISTER,
    INVITEUSER,
    PATH,
    COMPANY,
    TRANSACTIONS,
    MESSAGE,
    WITNESSES,
    ORDERS,
    CHATMESSAGES
}